<a href="https://colab.research.google.com/github/SamAugusto/R_programming/blob/main/Object_Oriented_Programming_in_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
methods("$<-")

 [1] $<-,data.frame-method         $<-,envRefClass-method       
 [3] $<-,localRefClass-method      $<-,refObjectGenerator-method
 [5] $<-.bibentry*                 $<-.citation*                
 [7] $<-.data.frame                $<-.person*                  
 [9] $<-.POSIXlt                   $<-.quosures*                
[11] $<-.rlang_ctxt_pronoun*       $<-.rlang_data_pronoun*      
[13] $<-.vctrs_list_of*            $<-.vctrs_rcrd*              
[15] $<-.vctrs_sclr*               $<-.vctrs_vctr*              
see '?methods' for accessing help and source code

In [3]:
x = matrix(1:10,nc=2)
rownames(x) = c("a","b","c","d","e")
x
class(x) = c("named_rows_matrix",class(x))


[,1] [,2]
a 1     6  
b 2     7  
c 3     8  
d 4     9  
e 5    10

In [4]:
"$<-.named_rows_matrix" = function(x,name,value){
  stopifnot(is.matrix(x))
  rn <- rownames(x)
  if (is.null(rn) || !(name %in% rn)) {
    stop(sprintf("row name %s not found", name))
  }

  # 2. validate the value length
  if (length(value) != ncol(x)) {
    stop(sprintf("value must have length %d", ncol(x)))
  }
  x[name,] = value
  x
}

In [5]:
x$a <- c(10, 20)

In [6]:
x

[,1] [,2]
a 10   20  
b  2    7  
c  3    8  
d  4    9  
e  5   10

In [7]:
x <- matrix(1:6, nrow = 3, byrow = TRUE)
rownames(x) <- c("a", "b", "c")
class(x) <- c("named_rows_matrix", class(x))

x$a <- c(9, 9)
x

[,1] [,2]
a 9    9   
b 3    4   
c 5    6

In [8]:
setClass("A", representation(s1="numeric"),prototype = prototype(s1 = 0))
myA = new("A")
myA
m2 = new("A",s1 = 10)
m2

An object of class "A"
Slot "s1":
[1] 0


An object of class "A"
Slot "s1":
[1] 10


In [9]:
setClass("B",contains = "A",representation(s2 = "character"),prototype = list(s2 = "hi"))
myB = new("B")
myB

An object of class "B"
Slot "s2":
[1] "hi"

Slot "s1":
[1] 0


In [10]:
setClass("Ohno",representation(y="numeric"))
getClass("Ohno")
removeClass("Ohno")
tryCatch(getClass("Ohno"),error = function(x) "Ohno is gone")

Class "Ohno" [in ".GlobalEnv"]

Slots:
              
Name:        y
Class: numeric

[1] TRUE

[1] "Ohno is gone"

In [11]:
getSlots("A")
slotNames("A")

s1 
"numeric"

[1] "s1"

In [12]:
extends("B")

[1] "B" "A"

In [14]:
install.packages("RBioinf")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Warning message:
“package ‘RBioinf’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages”


In [16]:
getClass("matrix")
extends("matrix")

Class "matrix" [package "methods"]

No Slots, prototype of class "matrix"

Extends: 
Class "array", directly
Class "structure", by class "array", distance 2
Class "vector", by class "array", distance 3, with explicit coerce

Known Subclasses: "mts"

[1] "matrix"    "array"     "structure" "vector"

In [24]:
myb = new("B")
as(myb,"A")


An object of class "A"
Slot "s1":
[1] 0


In [26]:
mya = new("A",s1=20)
as(myb,"A") <- mya
myb

An object of class "B"
Slot "s2":
[1] "hi"

Slot "s1":
[1] 20


In [38]:
setClass("Ex1",representation(s1="numeric"),prototype =prototype(s1=rnorm(10) ))

In [39]:
b = new("Ex1")
b

An object of class "Ex1"
Slot "s1":
 [1]  1.88948886  0.92029154  0.89500535 -0.21892497 -1.01625342  0.29114548
 [7] -0.03064325  0.56060212  1.03362674  0.41272649


In [43]:
makeex = function(){
  obj = new("Ex1")
  obj@s1 = rnorm(10)

}
b2 = makeex()
b2

[1]  1.0525349 -1.2602957  0.9503563  0.2257925 -1.1518999 -0.9472937
 [7]  0.1889034 -1.2934282  0.2462608  0.3203768