<a href="https://colab.research.google.com/github/SamAugusto/R_programming/blob/main/Object_Oriented_Programming_in_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
methods("$<-")

 [1] $<-,data.frame-method         $<-,envRefClass-method       
 [3] $<-,localRefClass-method      $<-,refObjectGenerator-method
 [5] $<-.bibentry*                 $<-.citation*                
 [7] $<-.data.frame                $<-.person*                  
 [9] $<-.POSIXlt                   $<-.quosures*                
[11] $<-.rlang_ctxt_pronoun*       $<-.rlang_data_pronoun*      
[13] $<-.vctrs_list_of*            $<-.vctrs_rcrd*              
[15] $<-.vctrs_sclr*               $<-.vctrs_vctr*              
see '?methods' for accessing help and source code

In [34]:
x = matrix(1:10,nc=2)
rownames(x) = c("a","b","c","d","e")
x
class(x) = c("named_rows_matrix",class(x))


[,1] [,2]
a 1     6  
b 2     7  
c 3     8  
d 4     9  
e 5    10

In [35]:
"$<-.named_rows_matrix" = function(x,name,value){
  stopifnot(is.matrix(x))
  rn <- rownames(x)
  if (is.null(rn) || !(name %in% rn)) {
    stop(sprintf("row name %s not found", name))
  }

  # 2. validate the value length
  if (length(value) != ncol(x)) {
    stop(sprintf("value must have length %d", ncol(x)))
  }
  x[name,] = value
  x
}

In [36]:
x$a <- c(10, 20)

In [37]:
x

[,1] [,2]
a 10   20  
b  2    7  
c  3    8  
d  4    9  
e  5   10

In [33]:
x <- matrix(1:6, nrow = 3, byrow = TRUE)
rownames(x) <- c("a", "b", "c")
class(x) <- c("named_rows_matrix", class(x))

x$a <- c(9, 9)
x

[,1] [,2]
a 9    9   
b 3    4   
c 5    6